
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Aug  9 2026 22:10:20 BST (Aug  9 2026 21:10:20 UTC)

// Verification Directory fv/control 

module control(Done, F, CarryIn, LoadACC, LoadR0, LoadR1, LoadT, LoadR,
     SelACC, SelR1, SelR, EnableOp1, EnableOp2, EnableALU, Clock,
     nReset, Req, CarryOut);
  input Clock, nReset, Req, CarryOut;
  output Done, F, CarryIn, LoadACC, LoadR0, LoadR1, LoadT, LoadR,
       SelACC, SelR1, SelR, EnableOp1, EnableOp2, EnableALU;
  wire Clock, nReset, Req, CarryOut;
  wire Done, F, CarryIn, LoadACC, LoadR0, LoadR1, LoadT, LoadR, SelACC,
       SelR1, SelR, EnableOp1, EnableOp2, EnableALU;
  wire [3:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_28, n_31, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_40, n_42, n_44, n_45, n_46, n_48, n_49;
  scandtype \state_reg[0] (.nReset (nReset), .Clock (Clock), .D (n_49),
       .Q (state[0]), .nQ (n_23));
  nand3 g1042__2398(.A (n_33), .B (n_48), .C (n_34), .Y (n_49));
  scandtype \state_reg[1] (.nReset (nReset), .Clock (Clock), .D (n_46),
       .Q (state[1]), .nQ (n_6));
  scandtype \state_reg[3] (.nReset (nReset), .Clock (Clock), .D (n_42),
       .Q (state[3]), .nQ (n_21));
  nand2 g1044__5107(.A (n_45), .B (n_38), .Y (n_48));
  nand3 g1046__6260(.A (n_10), .B (n_44), .C (n_7), .Y (EnableALU));
  nand3 g1047__4319(.A (n_31), .B (n_40), .C (n_9), .Y (n_46));
  nand2 g1049__8428(.A (n_0), .B (n_44), .Y (n_45));
  scandtype \state_reg[2] (.nReset (nReset), .Clock (Clock), .D (n_37),
       .Q (state[2]), .nQ (n_16));
  nand2 g1053__5526(.A (n_44), .B (n_35), .Y (SelR));
  nand2 g1050__6783(.A (n_44), .B (n_28), .Y (n_42));
  inv g1063(.A (n_44), .Y (LoadR));
  nand2 g1064__3680(.A (CarryOut), .B (F), .Y (n_40));
  nand2 g1051__1617(.A (n_36), .B (n_24), .Y (LoadR0));
  nand2 g1068__2802(.A (n_38), .B (state[3]), .Y (n_44));
  nand2 g1052__1705(.A (n_36), .B (n_35), .Y (n_37));
  nand3 g1054__5122(.A (n_23), .B (n_22), .C (n_21), .Y (n_34));
  nand2 g1058__8246(.A (n_4), .B (F), .Y (n_33));
  inv g1061(.A (n_25), .Y (Done));
  inv g1056(.A (n_31), .Y (LoadR1));
  inv g1062(.A (n_26), .Y (LoadACC));
  inv g1069(.A (n_28), .Y (LoadT));
  inv g1055(.A (n_19), .Y (EnableOp1));
  nand2 g1066__7098(.A (n_5), .B (n_18), .Y (n_26));
  nand3 g1065__6131(.A (state[0]), .B (n_13), .C (state[3]), .Y (n_25));
  nand3 g1067__1881(.A (n_23), .B (n_15), .C (state[1]), .Y (n_24));
  inv g1070(.A (n_22), .Y (n_38));
  nand3 g1060__5115(.A (n_23), .B (n_8), .C (n_21), .Y (n_31));
  inv g1075(.A (n_12), .Y (SelACC));
  nand2 g1057__7482(.A (n_18), .B (n_16), .Y (n_19));
  inv g1077(.A (n_35), .Y (CarryIn));
  nand2 g1059__4733(.A (n_11), .B (n_16), .Y (n_36));
  nand3 g1072__6161(.A (state[0]), .B (n_15), .C (state[1]), .Y (n_28));
  inv g1071(.A (n_14), .Y (F));
  nand2 g1074__9315(.A (n_15), .B (n_6), .Y (n_14));
  nand2 g1073__9945(.A (n_13), .B (n_23), .Y (n_22));
  nand2 g1079__2883(.A (n_15), .B (state[0]), .Y (n_12));
  nand2 g1081__2346(.A (n_15), .B (n_1), .Y (n_35));
  inv g1076(.A (n_10), .Y (n_11));
  inv g1078(.A (n_9), .Y (n_18));
  inv g1086(.A (n_2), .Y (n_8));
  inv g1087(.A (n_7), .Y (n_15));
  nand3 g1082__1666(.A (n_21), .B (state[0]), .C (n_6), .Y (n_9));
  nand3 g1080__7410(.A (state[1]), .B (state[0]), .C (n_21), .Y (n_10));
  inv g1083(.A (n_3), .Y (n_13));
  nand2 g1084__6417(.A (n_4), .B (state[2]), .Y (n_5));
  nand2 g1090__5477(.A (state[2]), .B (n_21), .Y (n_7));
  nand2 g1085__2398(.A (n_6), .B (n_16), .Y (n_3));
  nand2 g1088__5107(.A (state[1]), .B (n_16), .Y (n_2));
  nand2 g1089__6260(.A (state[0]), .B (state[1]), .Y (n_1));
  inv g1092(.A (CarryOut), .Y (n_4));
  inv g1091(.A (Req), .Y (n_0));
  buffer rm_assigns_buf_SelR1(.A (F), .Y (SelR1));
  buffer rm_assigns_buf_EnableOp2(.A (LoadR1), .Y (EnableOp2));
endmodule

